### ISSUE TITLE
how to get object properties of swing app fields?(Swingspy!)

### ISSUE THREAD

**Issue by SanjeevKumarmn** [jalian-systems/javadriver-examples#1]
how to get object properties of swing app fields? Similar to UISPY.exe or inspect.exe or F12 developer options for browser. As a functional tester, i do not have  access to the AUT code to pickup the swing app java class and that's why the java driver that is build with executable mode of web start / bat file start are really helpful. However, let me know there are any tools that can spy java components and gets the properties for the automation testing? I tried couple of ones from Github, but they do not pickup/ identify the already opened swing app.

**Comment by kdmurthy** [comment]
The javadriver is part of marathon. Marathon is a functional testing tool. You can use the assertion dialog while recording using Marathon to look at object properties.

**Comment by SanjeevKumarmn** [comment]
Thanks Murthy
